### ISSUE TITLE
Please consider adding Flutter support

### ISSUE THREAD

**Issue by jonny7737** [mintware-de/dart-json#1]
Or removing the mirrors dependancy.

Thank you.

**Comment by jonny7737** [comment]
I put more effort into this and find that I no longer need this package.

Thanks.

**Comment by cedvdb** [comment]
So this package doesn't work with flutter ? Shame, it's more elegant than the generator by google

**Comment by devtronic** [comment]
@cedvdb unfortunately [Flutter doesn't support the mirrors package](https://github.com/flutter/flutter/issues/1150) which makes this package elegant.
